root: true

env:
  es6: true
  browser: true
  node: true

globals:
  ga: false
  FB: false
  Rollbar: false
  __DEV__: false

parser: babel-eslint

plugins:
  - react

ecmaFeatures:
  jsx: true
  modules: true

extends:
  - eslint:recommended
  - plugin:react/recommended

rules:
  array-bracket-spacing: [2, never]
  arrow-spacing: 2
  arrow-parens: 2
  block-spacing: [2, always]
  brace-style: 2
  comma-dangle: [2, always-multiline]
  comma-spacing: [2, {before: false, after: true}]
  comma-style: [2, last]
  computed-property-spacing: [2, never]
  consistent-this: [2, self]
  consistent-return: 2
  dot-notation: 2
  dot-location: [2, property]
  eqeqeq: [2, smart]
  eol-last: 2
  indent: [2, 2, {SwitchCase: 1}]
  id-blacklist: [2, e]
  jsx-quotes: [2, prefer-double]
  keyword-spacing: 2
  key-spacing: 2
  linebreak-style: [2, unix]
  new-cap: 2
  no-case-declarations: 0
  no-unused-expressions: 2
  no-unused-vars: 2
  no-shadow: 2
  no-spaced-func: 2
  no-multi-spaces: 2
  no-undef: 2
  no-empty-pattern: 2
  no-dupe-keys: 2
  no-dupe-args: 2
  no-duplicate-case: 2
  no-cond-assign: 2
  no-extra-semi: 2
  no-extra-boolean-cast: 2
  no-trailing-spaces: 0
  no-unneeded-ternary: 2
  no-unreachable: 2
  no-var: 2
  object-curly-spacing: [2, never]
  one-var: [2, never]
  padded-blocks: [2, never]
  prefer-arrow-callback: 2
  prefer-const: 2
  quotes: [2, single, avoid-escape]
  semi: [2, never]
  space-before-blocks: [2, always]
  space-before-function-paren: [2, never]
  space-infix-ops: 2
  space-unary-ops: [2, { words: true, nonwords: false }]
  yoda: 2
  #prefer-template: 2 # template literals in render() causes changed variables not being reflected
  #max-len: [2, 120, 4]
  no-console: 1 # warning only

  # JSX
  react/jsx-boolean-value: [2, always]
  react/jsx-closing-bracket-location: 2
  react/jsx-curly-spacing: 2
  react/jsx-equals-spacing: 2
  react/jsx-handler-names: 2
  react/jsx-indent-props: [2, 2]
  react/jsx-max-props-per-line: [2, {maximum: 5}]
  react/jsx-pascal-case: 2
  react/jsx-space-before-closing: 2
  react/jsx-wrap-multilines: 2
  react/jsx-indent: [2, 2]
  #react/jsx-no-bind: 2 #TODO

  # React
  react/no-multi-comp: 2
  react/prefer-es6-class: 2
  react/self-closing-comp: 2
  react/sort-comp: 2
