export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

export const JOIN_REQUEST = 'JOIN_REQUEST'
export const JOIN_SUCCESS = 'JOIN_SUCCESS'
export const JOIN_FAILURE = 'JOIN_FAILURE'

export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'

export const GET_INVITE_REQUEST = 'GET_INVITE_REQUEST'
export const GET_INVITE_SUCCESS = 'GET_INVITE_SUCCESS'
export const GET_INVITE_FAILURE = 'GET_INVITE_FAILURE'
