export const TOGGLE_MENU = 'TOGGLE_MENU'
export const RESIZE = 'RESIZE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_DESTINATION = 'LOGIN_DESTINATION'

export const PASSWORD_REQUEST = 'PASSWORD_REQUEST'
export const PASSWORD_SUCCESS = 'PASSWORD_SUCCESS'
export const PASSWORD_FAILURE = 'PASSWORD_FAILURE'

export const GET_RESET_REQUEST = 'GET_RESET_REQUEST'
export const GET_RESET_SUCCESS = 'GET_RESET_SUCCESS'
export const GET_RESET_FAILURE = 'GET_RESET_FAILURE'

export const RESET_REQUEST = 'RESET_REQUEST'
export const RESET_SUCCESS = 'RESET_SUCCESS'
export const RESET_FAILURE = 'RESET_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

export const INVITE_REQUEST = 'INVITE_REQUEST'
export const INVITE_SUCCESS = 'INVITE_SUCCESS'
export const INVITE_FAILURE = 'INVITE_FAILURE'

export const JOIN_REQUEST = 'JOIN_REQUEST'
export const JOIN_SUCCESS = 'JOIN_SUCCESS'
export const JOIN_FAILURE = 'JOIN_FAILURE'

export const UPDATE_JOIN_DATA = 'UPDATE_JOIN_DATA'
export const UPDATE_LANG = 'UPDATE_LANG'

export const GET_MEMBER_REQUEST = 'GET_MEMBER_REQUEST'
export const GET_MEMBER_SUCCESS = 'GET_MEMBER_SUCCESS'
export const GET_MEMBER_FAILURE = 'GET_MEMBER_FAILURE'

export const GET_INVITE_REQUEST = 'GET_INVITE_REQUEST'
export const GET_INVITE_SUCCESS = 'GET_INVITE_SUCCESS'
export const GET_INVITE_FAILURE = 'GET_INVITE_FAILURE'

export const GET_ACTIVITY_REQUEST = 'GET_ACTIVITY_REQUEST'
export const GET_ACTIVITY_SUCCESS = 'GET_ACTIVITY_SUCCESS'
export const GET_ACTIVITY_FAILURE = 'GET_ACTIVITY_FAILURE'

export const GET_INVITES_REQUEST = 'GET_INVITES_REQUEST'
export const GET_INVITES_SUCCESS = 'GET_INVITES_SUCCESS'
export const GET_INVITES_FAILURE = 'GET_INVITES_FAILURE'

export const COMMENT_REQUEST = 'COMMENT_REQUEST'
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS'
export const COMMENT_FAILURE = 'COMMENT_FAILURE'
export const UPDATE_COMMENT_TEXT = 'UPDATE_COMMENT_TEXT'

export const UPDATE_INVITE_DATA = 'UPDATE_INVITE_DATA'

export const SWITCH_REQUEST = 'SWITCH_REQUEST'
export const SWITCH_SUCCESS = 'SWITCH_SUCCESS'
export const SWITCH_FAILURE = 'SWITCH_FAILURE'
