export const TOGGLE_MENU = 'TOGGLE_MENU'
export const TOGGLE_TRIBES = 'TOGGLE_TRIBES'
export const RESIZE = 'RESIZE'
export const SNACK_MESSAGE = 'SNACK_MESSAGE'
export const CLOSE_SNACK = 'CLOSE_SNACK'

export const UPDATE_JOIN_DATA = 'UPDATE_JOIN_DATA'
export const UPDATE_LANG = 'UPDATE_LANG'

export const LOGIN_DESTINATION = 'LOGIN_DESTINATION'

export const PASSWORD_SUCCESS = 'PASSWORD_SUCCESS'

export const PUT_PROFILE_SUCCESS = 'PUT_PROFILE_SUCCESS'

export const PUT_TRIBE_SUCCESS = 'PUT_TRIBE_SUCCESS'


export const GET_RESET_REQUEST = 'GET_RESET_REQUEST'
export const GET_RESET_SUCCESS = 'GET_RESET_SUCCESS'
export const GET_RESET_FAILURE = 'GET_RESET_FAILURE'


export const INVITE_REQUEST = 'INVITE_REQUEST'
export const INVITE_SUCCESS = 'INVITE_SUCCESS'
export const INVITE_FAILURE = 'INVITE_FAILURE'

export const GET_INVITES_REQUEST = 'GET_INVITES_REQUEST'
export const GET_INVITES_SUCCESS = 'GET_INVITES_SUCCESS'
export const GET_INVITES_FAILURE = 'GET_INVITES_FAILURE'


export const GET_MEMBER_REQUEST = 'GET_MEMBER_REQUEST'
export const GET_MEMBER_SUCCESS = 'GET_MEMBER_SUCCESS'
export const GET_MEMBER_FAILURE = 'GET_MEMBER_FAILURE'

export const GET_INVITE_REQUEST = 'GET_INVITE_REQUEST'
export const GET_INVITE_SUCCESS = 'GET_INVITE_SUCCESS'
export const GET_INVITE_FAILURE = 'GET_INVITE_FAILURE'

export const GET_ACTIVITY_REQUEST = 'GET_ACTIVITY_REQUEST'
export const GET_ACTIVITY_SUCCESS = 'GET_ACTIVITY_SUCCESS'
export const GET_ACTIVITY_FAILURE = 'GET_ACTIVITY_FAILURE'


export const GET_BILLS_REQUEST = 'GET_BILLS_REQUEST'
export const GET_BILLS_SUCCESS = 'GET_BILLS_SUCCESS'
export const GET_BILLS_FAILURE = 'GET_BILLS_FAILURE'

export const NEW_BILL_SUCCESS = 'NEW_BILL_SUCCESS'
export const PUT_BILL_SUCCESS = 'PUT_BILL_SUCCESS'

export const GET_BILL_REQUEST = 'GET_BILL_REQUEST'
export const GET_BILL_SUCCESS = 'GET_BILL_SUCCESS'
export const GET_BILL_FAILURE = 'GET_BILL_FAILURE'

export const DELETE_BILL_REQUEST = 'DELETE_BILL_REQUEST'
export const DELETE_BILL_SUCCESS = 'DELETE_BILL_SUCCESS'
export const DELETE_BILL_FAILURE = 'DELETE_BILL_FAILURE'


export const GET_NOTES_REQUEST = 'GET_NOTES_REQUEST'
export const GET_NOTES_SUCCESS = 'GET_NOTES_SUCCESS'
export const GET_NOTES_FAILURE = 'GET_NOTES_FAILURE'

export const PUT_NOTE_REQUEST = 'PUT_NOTE_REQUEST'
export const PUT_NOTE_SUCCESS = 'PUT_NOTE_SUCCESS'
export const PUT_NOTE_FAILURE = 'PUT_NOTE_FAILURE'

export const DELETE_NOTE_REQUEST = 'DELETE_NOTE_REQUEST'
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS'
export const DELETE_NOTE_FAILURE = 'DELETE_NOTE_FAILURE'

export const NEW_NOTE_REQUEST = 'NEW_NOTE_REQUEST'
export const NEW_NOTE_SUCCESS = 'NEW_NOTE_SUCCESS'
export const NEW_NOTE_FAILURE = 'NEW_NOTE_FAILURE'

export const MOVE_NOTE = 'MOVE_NOTE'


export const COMMENT_REQUEST = 'COMMENT_REQUEST'
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS'
export const COMMENT_FAILURE = 'COMMENT_FAILURE'
export const UPDATE_COMMENT_TEXT = 'UPDATE_COMMENT_TEXT'


export const SWITCH_REQUEST = 'SWITCH_REQUEST'
export const SWITCH_SUCCESS = 'SWITCH_SUCCESS'
export const SWITCH_FAILURE = 'SWITCH_FAILURE'


export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'
