# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'tribeez' do
  use_frameworks!

  pod 'Firebase'
  pod 'Firebase/Messaging'
  pod 'Rollbar'

  target 'tribeezTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
