# this extends the root config:

env:
  es6: true
  node: true

globals:
  __DEV__: false

plugins:
  - react
  - react-native

rules:
  # React Native
  react-native/no-unused-styles: 2
  react-native/split-platform-components: 2
  react-native/no-inline-styles: 2
  react-native/no-color-literals: 2
