// app:
export const TOGGLE_MENU = 'TOGGLE_MENU'
export const TOGGLE_TRIBES = 'TOGGLE_TRIBES'
export const RESIZE = 'RESIZE'
export const SNACK_MESSAGE = 'SNACK_MESSAGE'
export const CLOSE_SNACK = 'CLOSE_SNACK'
export const UPDATE_LANG = 'UPDATE_LANG'
export const ALERT = 'ALERT'
export const CLOSE_ALERT = 'CLOSE_ALERT'
export const CONFIG = 'CONFIG'

// Firebase events:
export const LOGGED_IN = 'LOGGED_IN'
export const LOGGED_OUT = 'LOGGED_OUT'

export const REQUEST = 'REQUEST'
export const SUCCESS = 'SUCCESS'
export const FAILURE = 'FAILURE'

export const TRIBE_UPDATED = 'TRIBE_UPDATED'
export const USER_UPDATED = 'USER_UPDATED'
export const MEMBER_ADDED = 'MEMBER_ADDED'
export const MEMBER_UPDATED = 'MEMBER_UPDATED'
export const MEMBERS_REMOVED = 'MEMBERS_REMOVED'

export const UNREAD = 'UNREAD'

export const ACTIVITY = 'ACTIVITY'
export const ACTIVITY_ADDED = 'ACTIVITY_ADDED'
export const ACTIVITY_CHANGED = 'ACTIVITY_CHANGED'
export const ACTIVITY_REMOVED = 'ACTIVITY_REMOVED'
export const ACTIVITY_CLEAR = 'ACTIVITY_CLEAR'
export const ACTIVITY_LOADED = 'ACTIVITY_LOADED'


// other events:

export const LOGIN_DESTINATION = 'LOGIN_DESTINATION'
export const LOGIN_EMAIL = 'LOGIN_EMAIL'

export const PASSWORD_SUCCESS = 'PASSWORD_SUCCESS'

export const GET_INVITE_SUCCESS = 'GET_INVITE_SUCCESS'

// notes:
export const GET_NOTES_SUCCESS = 'GET_NOTES_SUCCESS'
export const PUT_NOTE_SUCCESS = 'PUT_NOTE_SUCCESS'
export const MOVE_NOTE = 'MOVE_NOTE'

export const ITEM = 'ITEM'
export const UPDATE_COMMENT_TEXT = 'UPDATE_COMMENT_TEXT'
export const ITEM_CLEAR = 'ITEM_CLEAR'


//TODO: refacto:

export const INVITE_REQUEST = 'INVITE_REQUEST'
export const INVITE_SUCCESS = 'INVITE_SUCCESS'
export const INVITE_FAILURE = 'INVITE_FAILURE'


export const DELETE_EVENT_REQUEST = 'DELETE_EVENT_REQUEST'
export const DELETE_EVENT = 'DELETE_EVENT'
export const DELETE_EVENT_FAILURE = 'DELETE_EVENT_FAILURE'

export const DELETE_POLL_REQUEST = 'DELETE_POLL_REQUEST'
export const DELETE_POLL = 'DELETE_POLL'
export const DELETE_POLL_FAILURE = 'DELETE_POLL_FAILURE'

export const POST_VOTE_REQUEST = 'POST_VOTE_REQUEST'
export const POST_VOTE_SUCCESS = 'POST_VOTE_SUCCESS'
export const POST_VOTE_FAILURE = 'POST_VOTE_FAILURE'


export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST'
export const DELETE_TASK = 'DELETE_TASK'
export const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE'

export const POST_DONE_REQUEST = 'POST_DONE_REQUEST'
export const POST_DONE_SUCCESS = 'POST_DONE_SUCCESS'
export const POST_DONE_FAILURE = 'POST_DONE_FAILURE'
