export const TOGGLE_MENU = 'TOGGLE_MENU'
export const TOGGLE_TRIBES = 'TOGGLE_TRIBES'
export const RESIZE = 'RESIZE'
export const SNACK_MESSAGE = 'SNACK_MESSAGE'
export const CLOSE_SNACK = 'CLOSE_SNACK'

export const UPDATE_JOIN_DATA = 'UPDATE_JOIN_DATA'
export const UPDATE_LANG = 'UPDATE_LANG'

export const LOGIN_DESTINATION = 'LOGIN_DESTINATION'

export const PASSWORD_SUCCESS = 'PASSWORD_SUCCESS'

export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'

export const UPDATE_TRIBE_SUCCESS = 'UPDATE_TRIBE_SUCCESS'


export const GET_RESET_REQUEST = 'GET_RESET_REQUEST'
export const GET_RESET_SUCCESS = 'GET_RESET_SUCCESS'
export const GET_RESET_FAILURE = 'GET_RESET_FAILURE'


export const INVITE_REQUEST = 'INVITE_REQUEST'
export const INVITE_SUCCESS = 'INVITE_SUCCESS'
export const INVITE_FAILURE = 'INVITE_FAILURE'

export const GET_INVITES_REQUEST = 'GET_INVITES_REQUEST'
export const GET_INVITES_SUCCESS = 'GET_INVITES_SUCCESS'
export const GET_INVITES_FAILURE = 'GET_INVITES_FAILURE'


export const GET_MEMBER_REQUEST = 'GET_MEMBER_REQUEST'
export const GET_MEMBER_SUCCESS = 'GET_MEMBER_SUCCESS'
export const GET_MEMBER_FAILURE = 'GET_MEMBER_FAILURE'

export const GET_INVITE_REQUEST = 'GET_INVITE_REQUEST'
export const GET_INVITE_SUCCESS = 'GET_INVITE_SUCCESS'
export const GET_INVITE_FAILURE = 'GET_INVITE_FAILURE'

export const GET_ACTIVITY_REQUEST = 'GET_ACTIVITY_REQUEST'
export const GET_ACTIVITY_SUCCESS = 'GET_ACTIVITY_SUCCESS'
export const GET_ACTIVITY_FAILURE = 'GET_ACTIVITY_FAILURE'

export const GET_HISTORY_REQUEST = 'GET_HISTORY_REQUEST'
export const GET_HISTORY_SUCCESS = 'GET_HISTORY_SUCCESS'
export const GET_HISTORY_FAILURE = 'GET_HISTORY_FAILURE'


export const GET_BILLS_REQUEST = 'GET_BILLS_REQUEST'
export const GET_BILLS_SUCCESS = 'GET_BILLS_SUCCESS'
export const GET_BILLS_FAILURE = 'GET_BILLS_FAILURE'

export const NEW_BILL = 'NEW_BILL' // form
export const UPDATE_BILL = 'UPDATE_BILL' // form

export const GET_BILL_REQUEST = 'GET_BILL_REQUEST'
export const GET_BILL_SUCCESS = 'GET_BILL_SUCCESS'
export const GET_BILL_FAILURE = 'GET_BILL_FAILURE'

export const DELETE_BILL_REQUEST = 'DELETE_BILL_REQUEST'
export const DELETE_BILL = 'DELETE_BILL'
export const DELETE_BILL_FAILURE = 'DELETE_BILL_FAILURE'


export const GET_NOTES_REQUEST = 'GET_NOTES_REQUEST'
export const GET_NOTES_SUCCESS = 'GET_NOTES_SUCCESS'
export const GET_NOTES_FAILURE = 'GET_NOTES_FAILURE'

export const PUT_NOTE_REQUEST = 'PUT_NOTE_REQUEST'
export const PUT_NOTE_SUCCESS = 'PUT_NOTE_SUCCESS'
export const PUT_NOTE_FAILURE = 'PUT_NOTE_FAILURE'

export const DELETE_NOTE_REQUEST = 'DELETE_NOTE_REQUEST'
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS'
export const DELETE_NOTE_FAILURE = 'DELETE_NOTE_FAILURE'

export const NEW_NOTE_REQUEST = 'NEW_NOTE_REQUEST'
export const NEW_NOTE_SUCCESS = 'NEW_NOTE_SUCCESS'
export const NEW_NOTE_FAILURE = 'NEW_NOTE_FAILURE'

export const MOVE_NOTE = 'MOVE_NOTE'


export const GET_EVENTS_REQUEST = 'GET_EVENTS_REQUEST'
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS'
export const GET_EVENTS_FAILURE = 'GET_EVENTS_FAILURE'

export const GET_UPCOMING_EVENTS_REQUEST = 'GET_UPCOMING_EVENTS_REQUEST'
export const GET_UPCOMING_EVENTS_SUCCESS = 'GET_UPCOMING_EVENTS_SUCCESS'
export const GET_UPCOMING_EVENTS_FAILURE = 'GET_UPCOMING_EVENTS_FAILURE'

export const GET_PAST_EVENTS_REQUEST = 'GET_PAST_EVENTS_REQUEST'
export const GET_PAST_EVENTS_SUCCESS = 'GET_PAST_EVENTS_SUCCESS'
export const GET_PAST_EVENTS_FAILURE = 'GET_PAST_EVENTS_FAILURE'

export const NEW_EVENT = 'NEW_EVENT' // form
export const UPDATE_EVENT = 'UPDATE_EVENT' // form

export const GET_EVENT_REQUEST = 'GET_EVENT_REQUEST'
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS'
export const GET_EVENT_FAILURE = 'GET_EVENT_FAILURE'

export const DELETE_EVENT_REQUEST = 'DELETE_EVENT_REQUEST'
export const DELETE_EVENT = 'DELETE_EVENT'
export const DELETE_EVENT_FAILURE = 'DELETE_EVENT_FAILURE'


export const GET_POLLS_REQUEST = 'GET_POLLS_REQUEST'
export const GET_POLLS_SUCCESS = 'GET_POLLS_SUCCESS'
export const GET_POLLS_FAILURE = 'GET_POLLS_FAILURE'

export const GET_POLL_REQUEST = 'GET_POLL_REQUEST'
export const GET_POLL_SUCCESS = 'GET_POLL_SUCCESS'
export const GET_POLL_FAILURE = 'GET_POLL_FAILURE'

export const NEW_POLL = 'NEW_POLL' // form
export const UPDATE_POLL = 'UPDATE_POLL' // form

export const DELETE_POLL_REQUEST = 'DELETE_POLL_REQUEST'
export const DELETE_POLL = 'DELETE_POLL'
export const DELETE_POLL_FAILURE = 'DELETE_POLL_FAILURE'

export const POST_VOTE_REQUEST = 'POST_VOTE_REQUEST'
export const POST_VOTE_SUCCESS = 'POST_VOTE_SUCCESS'
export const POST_VOTE_FAILURE = 'POST_VOTE_FAILURE'


export const GET_TASKS_REQUEST = 'GET_TASKS_REQUEST'
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS'
export const GET_TASKS_FAILURE = 'GET_TASKS_FAILURE'

export const GET_TASK_REQUEST = 'GET_TASK_REQUEST'
export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS'
export const GET_TASK_FAILURE = 'GET_TASK_FAILURE'

export const NEW_TASK = 'NEW_TASK' // form
export const UPDATE_TASK = 'UPDATE_TASK' // form

export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST'
export const DELETE_TASK = 'DELETE_TASK'
export const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE'

export const POST_DONE_REQUEST = 'POST_DONE_REQUEST'
export const POST_DONE_SUCCESS = 'POST_DONE_SUCCESS'
export const POST_DONE_FAILURE = 'POST_DONE_FAILURE'


export const GET_LOG_REQUEST = 'GET_LOG_REQUEST'
export const GET_LOG_SUCCESS = 'GET_LOG_SUCCESS'
export const GET_LOG_FAILURE = 'GET_LOG_FAILURE'

export const COMMENT_REQUEST = 'COMMENT_REQUEST'
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS'
export const COMMENT_FAILURE = 'COMMENT_FAILURE'

export const UPDATE_COMMENT_TEXT = 'UPDATE_COMMENT_TEXT'


export const SWITCH_REQUEST = 'SWITCH_REQUEST'
export const SWITCH_SUCCESS = 'SWITCH_SUCCESS'
export const SWITCH_FAILURE = 'SWITCH_FAILURE'


export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'
